dataset_params:
  data_dir: "/data/kanvari/fastMRI/multicoil_train"
  contrasts: ["t2"]
  train_split: "train"
  val_split: "val"
  test_split: "test"
  batch_size: 2
  num_workers: 4
  trim_top_bottom_frac: 0.2
  resize_after_trim: true
  nx: 320
  ny: 320
  image_key: "reconstruction_rss"
  kspace_key: "kspace"
  split_json: "/home/kanvari/fastMRI_denoising_repo/split/fastmri_t2_split.json"
  max_train_files: null
  max_val_files: null
  max_test_files: null
  max_slices_per_volume: null

simulation_params:
  noise_std: 0.00001
  noise_std_choices: [0.00001, 0.00002, 0.00005]
  eval_noise_stds: [0.00001, 0.00002, 0.00005]
  apply_contrast: true
  gamma: 0.70
  contrast_gamma: 0.70
  noise_std_range: null
  gamma_range: null
  contrast_gamma_range: null
  deterministic_eval: true

model:
  type: "swinir"
  variant: "medium_320"

training_params:
  seed: 42
  sanity_check: false
  sanity_data_dir: "./deta_demo"
  sanity_max_files: null
  sanity_use_split_json: false
  sanity_max_epochs: 5
  sanity_batch_size: 1
  sanity_num_workers: 0
  sanity_log_every_n_steps: 1

  lr: 0.0003
  weight_decay: 0.00001
  image_loss: "ssim"
  kspace_loss: "l1"
  lambda_image: 1.0
  lambda_kspace: 0.1
  max_epochs: 100
  accelerator: "auto"
  devices: "auto"
  precision: "32"
  log_every_n_steps: 20
  run_test: true
  early_stopping_patience: 10
  early_stopping_min_delta: 0.0

logging_params:
  project: "fastmri_brain_denoise"
  run_name: "swinir_baseline"
  default_root_dir: "fastMRI_denoising_repo/logs"
  wandb_mode: "online"
  wandb_entity: null
  wandb_log_model: false
  val_image_log_count: 4
  val_image_log_every_n_epochs: 1
  test_log_all_images: true
  log_triplets_to_wandb: true
  save_triplet_panels_locally: false
  save_triplets_locally: true
  triplet_output_dir: "fastMRI_denoising_repo/outputs/test_image_logger"
